from database.models.group import Group
from database.models.quantorium import Quantorium
from database.models.quantum import Quantum
from database.models.user import User
from database.models.admin import Admin
from database.models.education_material import EducationMaterial
from database.models.group import Group
from database.models.lesson import Lesson
from database.models.news import News
from database.models.note import Note
from database.models.project import Project
from database.models.reason import Reason
from database.models.representative import Representative
from database.models.role import Role
from database.models.room import Room
from database.models.schedule_item import ScheduleItem
from database.models.student_presence import StudentPresence
from database.models.student_project_link import StudentProjectLink
from database.models.student_quantum_link import StudentQuantumLink
from database.models.student import Student
from database.models.teacher import Teacher
from database.models.recovery import Recovery
